### ISSUE TITLE
Update installation method

### ISSUE THREAD

**Issue by Enn3Developer** [ClueLang/Clue#10]
To build and install the compiler on Linux simply do ```git clone https://github.com/ClueLang/Clue.git && cd clue && cargo install --path .```
For other OS, it should be similar to this command

**Comment by Enn3Developer** [comment]
If you have cargo it automatically add Clue to PATH because the installation happens in `.cargo/bin`

**Comment by Maiori44** [comment]
ooh, my bad, I didn't know that
it's fine then, I'll add it to the README
