### ISSUE TITLE
Condition indexing breaks on loop conditions

### ISSUE THREAD

**Issue by Maiori44** [ClueLang/Clue#100]
The following code:
```
local a = {}
while !(a?.b) {
	a = {b = true}
}
```
Will compile to:
```lua
local a = {};
local _internal0 = a;
while not (_internal0 and _internal0.b) do
        a = {
                b = true
        };
end
```
But since `a` is modified instead of `_internal0`, the condition will never be true even if it should.

**Comment by Markos-Th09** [comment]
The best solution for that would be to inline the _internal variable although it may complicate things

**Comment by Maiori44** [comment]
It would complicate things indeed
(And more than that too)

**Comment by Maiori44** [comment]
Solution was found.
```
local a = {}
while !(a?.b) {
	a = {b = true}
}
```
The above code will not compile into:
```lua
local a = {};
local function _internal1()
	local _internal0 = a;
	return not ((_internal0 and _internal0.b));
end
while _internal1() do
	a = {
		b = true
	};
end
```
