### ISSUE TITLE
Match blocks returning matched expression when no branch matches

### ISSUE THREAD

**Issue by Maiori44** [ClueLang/Clue#106]
```lua
local a = match "d" {
	1 => 2,
	true => false
}
print(a)
```
This is compiled to:
```lua
local _internal0 = "d";
if (_internal0 == 1) then
	_internal0 = 2;
elseif (_internal0 == true) then
	_internal0 = false;
end
local a = _internal0;
print(a);
```
Which means `a` will become `"d"`, as `"d"` did not match with any of the branches.
Should we leave this in? Or should we fix it somehow?

**Comment by Maiori44** [comment]
Maybe in the future, but since this is quite an issue we should fix it in 3.3 (maybe...)
An easy solution is to set _internal0 to nil using an `else` at the end, but should we?

**Comment by Enn3Developer** [comment]
That may be the right solution for now, but probably will break compatibility with 4.0 (if a better match will be implemented, but that's not so much a problem)

**Comment by Maiori44** [comment]
The main worry I have is that it technically could break compatibility with 3.2 as well, since some code may actually rely on this bug

**Comment by Enn3Developer** [comment]
It was never documented to do such a thing so I'd say that's better changing than not

**Comment by Maiori44** [comment]
Hm, true, we should fix it then yeah

**Comment by Markos-Th09** [comment]
Since this is intended behavior and is considered a bug we can fix it. I would say just set it to nil if nothing matches with an else block

**Comment by Maiori44** [comment]
I think you meant to say "Since this is not intended behaviour"?

**Comment by metamorphix** [comment]
Absolutely agree that if no cases match, the expression should evaluate to `nil`. Of all things that could happen, having it evaluate to the scrutinee probably has the highest "WTF" factor!

**Comment by metamorphix** [comment]
As for implementation, I imagine it shouldn't be too difficult as it is equivalent to there being an implicit:

```
_ => nil,
```

…at the end of every match block.

**Comment by Maiori44** [comment]
I *think* it should be easy enough to do, but I'm not sure.

**Comment by Maiori44** [comment]
a...warning?

**Comment by Markos-Th09** [comment]
at least if I made a linter it would be a warning, but to the context of only the compiler I guess it wouldn't be required

**Comment by Maiori44** [comment]
It should be best to just fix it altogether by setting it to nil, I think

**Comment by Markos-Th09** [comment]
> It should be best to just fix it altogether by setting it to nil, I think

It should be fixed but using this is sort of bad code

**Comment by Maiori44** [comment]
Clue never complains about bad code anywhere else, so...

**Comment by Markos-Th09** [comment]
> Clue never complains about bad code anywhere else, so...

on this should we make a linter for 4.0?

**Comment by Maiori44** [comment]
I think 4.0 is already a daunting task as is, maybe later on..

**Comment by metamorphix** [comment]
You could have a warning for cases where the user is clearly doing something that doesn't make sense (like the example in the original post), but it's more commonly going to happen accidentally. What's the use case for matching on a constant? If you're matching on a variable, then without a type system, you're not going to know if the match could fail.

**Comment by Maiori44** [comment]
having the fail be shown by returning the matched variable also doesn't help

**Comment by Maiori44** [comment]
This issue has now been fixed.
