### ISSUE TITLE
`for i in f, stop, initial` syntax

### ISSUE THREAD

**Issue by Markos-Th09** [ClueLang/Clue#122]
## Feature
Lua supports a syntax in for loops which looks like this
```lua
local f = function(s, i)
    if i == 10 then
        return s
    end
    return i + 1
end

for i in f, nil, 1 do
    print(i)
end
```

This is iterates over the iterator `f` with an initial value of `1` and a stopping value of `nil`. Although rarely used, Clue lacks this feature in for loops.

## Possible Implementations
This could be added to for...with loops

```lua
for i with f, nil, 1 {
    print(i)
}
```

## Alternatives
Alternatively this can be expanded to 
```lua
local i = 1
while true do
    i = f(nil, i)
    if i == nil then
        break
    end
    print(i)
end
```

or in the general case as referenced in the lua manual:

```lua
do
    local f, s, var = f, stop, initial
    while true do
        local var_1, ···, var_n = f(s, var)
        var = var_1
        if var == nil then break end
        -- block
    end
end
```

**Comment by Maiori44** [comment]
This has been added.
