### ISSUE TITLE
Commas in string `@macro` argument count as `@macro` arguments.

### ISSUE THREAD

**Issue by defaultzone** [ClueLang/Clue#126]
Faced a problem that I can't use commas in arguments (string type) of a macro.
As an example, if you compile this code (using `clue main.clue`):
```lua
@macro debugMessage(entryPoint, message) { print("[" .. $entryPoint .. "]: " .. message) }
$debugMessage!("somewhere", "Hello, world!")
```
then you will get the following error:
```
Error in main.clue:2:1!
Error: "Too many arguments passed to macro"
```

**Comment by Maiori44** [comment]
oh wow, what on oversight
I'll get a fix out ASAP

**Comment by Maiori44** [comment]
3.4.2 will contain the fix, it will be released soon
