### ISSUE TITLE
`@define` doesn't recognize strings?

### ISSUE THREAD

**Issue by defaultzone** [ClueLang/Clue#129]
```lua
@define url "https://google.com"

print($url)
```
```bash
[dzone@archlinux test]$ clue test.clue
Error in test.clue:3:13!
Error: "Unterminated string"
Error: "Cannot continue until the above errors are fixed"
```

**Comment by Maiori44** [comment]
Investigating this, it does not seem to be related to strings, but rather to the `//`.
```lua
@define url "https:google.com"

print($url)
```
```lua
@define url https://google.com

print($url)
```
While this gives a similar error.
It's like some error about how comments are read, will investigate now.

**Comment by Maiori44** [comment]
Turns out there was an oversight and `@define` had no special code to read strings, which caused these and other issues.
The issue has been fixed and a patch will be released shortly.
