### ISSUE TITLE
Use any whitespace in indentation of multiline regular strings

### ISSUE THREAD

**Issue by Lyrth** [ClueLang/Clue#131]
Currently, multiline regular strings trim away newlines and literal tab characters so that the string can be indented when multilined. Some (or most) editors insert multiple spaces instead of the tab character when the tab key is pressed, so it takes a bit more effort to get a tab character for use here.

For ergonomics, an alternative (possibly breaking change) is if the first `"` is immediately followed by a newline, the first sequence of spaces right after that newline (e.g. 4 spaces) will become the reference sequence spacing, that would be removed in the following lines. 
As an example, given:
```lua
local a = "
    this is a 
    regular string
        and maybe i need this spacing here
        and here too
    and back to no spacing

    hello
    world
"
```
it will become
```lua
local a = "this is aregular string    and maybe i need this spacing here    and here tooand back to no spacinghelloworld"
```

This might be unnecessary complexity or might be too confusing, so it should probably be a flag instead of being a default if implemented.

**Comment by Maiori44** [comment]
the flag could let you choose between X spaces or tabs, or between letting the preprocessor figure it out on its own on every file
But then, what should the default value of the flag be?

**Comment by Lyrth** [comment]
Having a set amount of whitespace (constant) might be detrimental since the string can be in any depth.
```lua
local a, b
if A {
    a = "
        hello
        world
    "
    if B {
        b = "
            and hello
            Clue
        "
    }
}
```
Probably best to make it figure it out on its own for each string.

**Comment by Maiori44** [comment]
okay, but what if someone does want a bit of spaces before? how could it tell the preprocessor "no wait stop a bit earlier"

**Comment by Maiori44** [comment]
> okay, but what if someone does want a bit of spaces before? how could it tell the preprocessor "no wait stop a bit earlier"

```lua
local str = "

  spaces will now be preserved
"
```
This would turn into:
`local str = "  spaces will now be preserved"`
So that's not an issue.
