### ISSUE TITLE
CLI stdin/stdout stream improvements

### ISSUE THREAD

**Issue by Lyrth** [ClueLang/Clue#132]
The clue executable should treat a single dash `-` in place of the filename as "read script from stdin." This option is also used on multiple Linux command-line utilities with the same usage, and allows pipelines like this:
`command /that/reads/a/file.clue | clue -t luajit - -o | luajit -`

On a similar note, `-o` flag should suppress info messages (or maybe redirect them into stderr) from the output code. Having `Compiled Lua code of file "(command line)":` and `Compiled file "(command line)" in 0.* seconds!` around the output makes the compiled code difficult to use for other purposes (i.e. sending the output to a Lua interpreter). Probably applies to `--struct` and `--token` options too.

**Comment by Maiori44** [comment]
Maybe there could be a `--suppress` flag that removes all unnecessary prints?

**Comment by Markos-Th09** [comment]
This is also most of the time called `--quiet` and `-q` for short

**Comment by Maiori44** [comment]
> This is also most of the time called `--quiet` and `-q` for short

Oh, yeah true

**Comment by Lyrth** [comment]
`--quiet` and `-q` is good, yes

**Comment by Lyrth** [comment]
Moved to #136

**Comment by Maiori44** [comment]
I'll close since it was moved
