### ISSUE TITLE
OOB Panic on specific arrangements of LuaJIT-style integer formats (LL/ULL)

### ISSUE THREAD

**Issue by Lyrth** [ClueLang/Clue#133]
Clue seems to support LuaJIT-style long integer literals (`256ULL`, `-4LL`, etc.), but parsing seems to trip up on certain arrangements of the literal. An example (newline included, works fine if `EOF` is immediately after ULL):
```lua
local a = 2ULL

```
panics with:
```
thread 'main' panicked at core\src\scanner.rs:180:18:
index out of bounds: the len is 14 but the index is 14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Different combinations of the lines before and after the usage produce odd results, and even `LL`'s behavior is very different from `ULL` in terms of what panics or not. There seems to be no clear pattern on how the panic happens, so perhaps the method of parsing should be changed.

 Here is a matrix of which arrangements error out (ones highlighted in red):
![image](https://github.com/ClueLang/Clue/assets/38674984/ad73d6c3-c802-49cf-8711-ff77df3df9fe)

**Comment by Maiori44** [comment]
Turns out the issue was the scanner not reading `ULL` and `LL` properly.
It has been fixed in 4.0
