### ISSUE TITLE
`goto` statement

### ISSUE THREAD

**Issue by defaultzone** [ClueLang/Clue#135]
Currently Clue doesn't have `goto` statements, but Lua does (on LuaJIT, >=Lua5.2 versions). In Clue this possible can implemented in c-style, like this:

```c
goto label
label: print("hi") // ::label:: print("hi")
```

**Comment by Maiori44** [comment]
~~How many versions of Lua support `goto` statements?~~ Your edit just answered that.
Using C-style syntax might make it look too similar to how types will be specified in Clue 4.0, but it should still be possible to implement.

**Comment by Maiori44** [comment]
`goto` statements have been added to 4.0 following the suggested syntax, thank you
