### ISSUE TITLE
debug flag causes invalid escape sequence error on windows

### ISSUE THREAD

**Issue by iAndyHD3** [ClueLang/Clue#144]
when `--debug` is used on windows it produces the following code for file paths:

`_errored_file = ".\main.clue"`,
`_errored_file = "C:\Users\...."`

which causes `Invalid escape sequence` error

solution: escape backwards slashes

**Comment by Maiori44** [comment]
This has been fixed by using `[[ ... ]]` strings which ignore escape sequences.
This fix will be present in the new patch.
