### ISSUE TITLE
Unsafe code

### ISSUE THREAD

**Issue by Enn3Developer** [ClueLang/Clue#15]
As of now, the code is littered of `unsafe`. The proposal is to change the code with the ultimate goal of removing all `unsafe` blocks from the codebase.
First of all, the `finaloutput` variable should not be global: there's no reason for it because there are other possible ways to achieve the same thing, some of those include better readability.
About the ENV variables, the same thing as above applies.

Possible solution: create a struct where everything could be loaded inside.

**Comment by Maiori44** [comment]
but then the struct would have to be global

**Comment by Maiori44** [comment]
hm, interesting
the reference would have to be mutable?

**Comment by Enn3Developer** [comment]
if you modify the values inside then yes

**Comment by Maiori44** [comment]
`finaloutput` is modified kinda often in the code

**Comment by Markos-Th09** [comment]
A singleton struct would be ideal in this case

**Comment by Maiori44** [comment]
I'm not sure if this should be done soon or in 3.0
Since it looks like it would require quite a refactor

**Comment by Markos-Th09** [comment]
> I'm not sure if this should be done soon or in 3.0 Since it looks like it would require quite a refactor

I don't think it needs to wait that much

**Comment by Enn3Developer** [comment]
I volunteer to work on this

**Comment by Enn3Developer** [comment]
@Maiori44 as the pr got merged, will you close this issue or leave it until 3.0?

**Comment by Maiori44** [comment]
guess it's no longer for 3.0, so I'll close it
