### ISSUE TITLE
Cargo build fails

### ISSUE THREAD

**Issue by bentxt** [ClueLang/Clue#150]
I try to run on macos

`cargo build`

And it fails with following errors:

```
   Compiling clue v3.4.7 (/.../clue/clue.git/cli)
error: linking with `cc` failed: exit status: 1
  |
  = note: env -u IPHONEOS_DEPLOYMENT_TARGET -u TVOS_DEPLOYMENT_TARGET -u
  XROS_DEPLOYMENT_TARGET LC_ALL="C"
  PATH="/usr/local/Cellar/rust/1.82.0/lib/rustlib/x86_64-apple-darwin/bin:/usr/local/Cellar/rust/1.82.0/lib/rustlib/x86_64-apple-darwin/bin:/usr/local/Cellar/rust/1.82.0/lib/rustlib/x86_64-apple-darwin/bin:/Users/ben/.bun/bin:/Users/ben/build/lobster/bin:/Users/ben/.opam/5.1.1/bin:/Users/ben/.opam/5.1.1/bin:/Users/ben/build/lunarml/lunarml/bin:/Users/ben/build/openjdk/jdk-22.jdk/Contents/Home/bin:/Users/ben/local/dlang/dmd2/osx/bin:/Users/ben/go/bin:/Applications/Racket
  v8.12/bin:/Users/ben/.cargo/bin:/Users/ben/.opam/default/bin:/Users/ben/build/bin:/Users/ben/.local/bin:/Users/ben/bin:/Users/ben/.bin:/Users/ben/local/bin:/opt/local/sbin:/opt/local/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/bin:/sbin:/usr/bin:/Users/ben/build/roc/roc_nightly-macos_x86_64-2024-04-30-db97e3e:/Users/ben/build/roc/roc_nightly-macos_x86_64-2024-04-30-db97e3e"
  VSLANG="1033" ZERO_AR_DATE="1" "cc" "-arch" "x86_64" "-m64"
  "/var/folders/2f/_9380nw966jbwjbc68_bw0mw0000gw/T/rustcni39jF/symbols.o"
  "/.../clue.git/target/debug/deps/clue-8eb2b540e34016e9.07s5yw3r2ywsd0la35w5n4s0o.rcgu.o"


  = note: ld: warning: object file (/../clue.git/target/debug/deps/libmlua_sys-630b4209ae30daf4.rlib[4](lj_vm.o)) was built for newer 'macOS' version (14.5) than being linked (14.0)
          ld: warning: object file (/../clue.git/target/debug/deps/librpmalloc_sys-0eb66e9d348672b8.rlib[4](d5750a48c4367597-rpmalloc.o)) was built for newer 'macOS' version (14.5) than being linked (14.0)
          Undefined symbols for architecture x86_64:
            "___emutls_get_address", referenced from:
                _lj_err_throw in libmlua_sys-630b4209ae30daf4.rlib[7](lj_err.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: could not compile `clue` (bin "clue") due to 1 previous error

```

**Comment by Markos-Th09** [comment]
> I try to run on macos
> 
> `cargo build`
> 
> And it fails with following errors:
> 
> ```
>    Compiling clue v3.4.7 (/.../clue/clue.git/cli)
> error: linking with `cc` failed: exit status: 1
>   |
>   = note: env -u IPHONEOS_DEPLOYMENT_TARGET -u TVOS_DEPLOYMENT_TARGET -u
>   XROS_DEPLOYMENT_TARGET LC_ALL="C"
>   PATH="/usr/local/Cellar/rust/1.82.0/lib/rustlib/x86_64-apple-darwin/bin:/usr/local/Cellar/rust/1.82.0/lib/rustlib/x86_64-apple-darwin/bin:/usr/local/Cellar/rust/1.82.0/lib/rustlib/x86_64-apple-darwin/bin:/Users/ben/.bun/bin:/Users/ben/build/lobster/bin:/Users/ben/.opam/5.1.1/bin:/Users/ben/.opam/5.1.1/bin:/Users/ben/build/lunarml/lunarml/bin:/Users/ben/build/openjdk/jdk-22.jdk/Contents/Home/bin:/Users/ben/local/dlang/dmd2/osx/bin:/Users/ben/go/bin:/Applications/Racket
>   v8.12/bin:/Users/ben/.cargo/bin:/Users/ben/.opam/default/bin:/Users/ben/build/bin:/Users/ben/.local/bin:/Users/ben/bin:/Users/ben/.bin:/Users/ben/local/bin:/opt/local/sbin:/opt/local/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/bin:/sbin:/usr/bin:/Users/ben/build/roc/roc_nightly-macos_x86_64-2024-04-30-db97e3e:/Users/ben/build/roc/roc_nightly-macos_x86_64-2024-04-30-db97e3e"
>   VSLANG="1033" ZERO_AR_DATE="1" "cc" "-arch" "x86_64" "-m64"
>   "/var/folders/2f/_9380nw966jbwjbc68_bw0mw0000gw/T/rustcni39jF/symbols.o"
>   "/.../clue.git/target/debug/deps/clue-8eb2b540e34016e9.07s5yw3r2ywsd0la35w5n4s0o.rcgu.o"
> 
> 
>   = note: ld: warning: object file (/../clue.git/target/debug/deps/libmlua_sys-630b4209ae30daf4.rlib[4](lj_vm.o)) was built for newer 'macOS' version (14.5) than being linked (14.0)
>           ld: warning: object file (/../clue.git/target/debug/deps/librpmalloc_sys-0eb66e9d348672b8.rlib[4](d5750a48c4367597-rpmalloc.o)) was built for newer 'macOS' version (14.5) than being linked (14.0)
>           Undefined symbols for architecture x86_64:
>             "___emutls_get_address", referenced from:
>                 _lj_err_throw in libmlua_sys-630b4209ae30daf4.rlib[7](lj_err.o)
>           ld: symbol(s) not found for architecture x86_64
>           clang: error: linker command failed with exit code 1 (use -v to see invocation)
>           
> 
> error: could not compile `clue` (bin "clue") due to 1 previous error
> ```
It looks like it is failing to link with an internal crt symbol. I will try to reproduce it today on mac os too. Have a tried a clean build?

**Comment by Markos-Th09** [comment]
I'm unable to reproduce this. Can you share more information such as rust version, mac os version and the commit?

**Comment by bentxt** [comment]
Hi, thanks for answering, here is a transcript of what I'm doing as I write

## Specs
```
$ sw_vers
ProductName:		macOS
ProductVersion:		14.6.1
BuildVersion:		23G93

$ rustc --version
rustc 1.82.0 (f6e511eec 2024-10-15) (Homebrew)

$ git log -1
commit 78ce10c1d7a985b294ce7d08ef03565cc956e3c1 (HEAD -> main, origin/main, origin/HEAD)
Author: Mads Hougesen <mads@mhouge.dk>
Date:   Fri Oct 11 17:20:51 2024 +0200

    docs: comming -> coming
```


## Transcript

```
rm -rf ~/.cargo/
mkdir -p builds/clue
 cd builds/clue
rm -rf *

git clone https://github.com/ClueLang/Clue clue.git
cd clue.git
[ ... initial errors ]
     ld: warning: object file (/](d5750a48c4367597-rpmalloc.o)) was built for newer 'macOS' version (14.5) than being linked (14.0)
          Undefined symbols for architecture x86_64:
            "___emutls_get_address", referenced from:
                _lj_err_throw in libmlua_sys-985156d34370faa6.rlib[7](lj_err.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by bentxt** [comment]
at the beginning of the error sections there is the line

```
error: linking with `cc` failed: exit status: 1
```

so this is the cc that is used
```
cc --version
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: x86_64-apple-darwin23.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by Markos-Th09** [comment]
> Hi, thanks for answering, here is a transcript of what I'm doing as I write
> 
> ## Specs
> ```
> $ sw_vers
> ProductName:		macOS
> ProductVersion:		14.6.1
> BuildVersion:		23G93
> 
> $ rustc --version
> rustc 1.82.0 (f6e511eec 2024-10-15) (Homebrew)
> 
> $ git log -1
> commit 78ce10c1d7a985b294ce7d08ef03565cc956e3c1 (HEAD -> main, origin/main, origin/HEAD)
> Author: Mads Hougesen <mads@mhouge.dk>
> Date:   Fri Oct 11 17:20:51 2024 +0200
> 
>     docs: comming -> coming
> ```
> 
> ## Transcript
> ```
> rm -rf ~/.cargo/
> mkdir -p builds/clue
>  cd builds/clue
> rm -rf *
> 
> git clone https://github.com/ClueLang/Clue clue.git
> cd clue.git
> [ ... initial errors ]
>      ld: warning: object file (/](d5750a48c4367597-rpmalloc.o)) was built for newer 'macOS' version (14.5) than being linked (14.0)
>           Undefined symbols for architecture x86_64:
>             "___emutls_get_address", referenced from:
>                 _lj_err_throw in libmlua_sys-985156d34370faa6.rlib[7](lj_err.o)
>           ld: symbol(s) not found for architecture x86_64
>           clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```

could be related to using rust from brew? that’s the only difference when I tried it as I had used rustup 
Edit: I still cannot reproduce it even with rust from homebrew

**Comment by Markos-Th09** [comment]
I still some deployment target weirdness though so just in case try upgrading xcode or command line tools.

**Comment by bentxt** [comment]
I made some tests to approve my environment. 

For example I was able to build the `tauri` project which is quite large.

**Comment by bentxt** [comment]
> I still some deployment target weirdness though so just in case try upgrading xcode or command line tools.

thats a good advice, I will do that, this was already a source of annoying errors in the past
thanks

**Comment by Markos-Th09** [comment]
If it doesn't build after that I unfortunately can't help you as I can't reproduce this exact error on a clean build with the same environment.

**Comment by bentxt** [comment]
> I unfortunately can't help

Yeah I understand ... I have updated my system and even reinstalled a lot of key elements, but still get the same error ...

Last question, if you look at my specs, do you see any significant deviation from your macos environment?

```
$ sw_vers
ProductName:		macOS
ProductVersion:		14.6.1
BuildVersion:		23G93

$ rustc --version
rustc 1.82.0 (f6e511eec 2024-10-15) (Homebrew)

$ git log -1
commit 78ce10c1d7a985b294ce7d08ef03565cc956e3c1 (HEAD -> main, origin/main, origin/HEAD)
```

**Comment by bentxt** [comment]
OK, I'm one step further, `cargo build` works in `bash`. So far I worked in fish shell. There might be something off with the way the linker "environment" (cc,ld, ...) is invoked.

**Comment by Markos-Th09** [comment]
> OK, I'm one step further, `cargo build` works in `bash`. So far I worked in fish shell. There might be something off with the way the linker "environment" (cc,ld, ...) is invoked.

does it work with fish on default configuration (`fish --no-config`)? if so, you should check your shell profile.

I use zsh, the default shell, for reference

**Comment by bentxt** [comment]
> fish --no-config

Good idea! Unfortunately the errors persisted. But then I went full `rm -rf ~/.config/fish` and now it works!

**Comment by bentxt** [comment]
As I said `rm -rf ~/.config/fish` solved the problem. Unfortunately I can no longer reproduce the error even after after having relinked fish files
