### ISSUE TITLE
Debug comments

### ISSUE THREAD

**Issue by Enn3Developer** [ClueLang/Clue#16]
Debug comments are useless in the compiled file unless used for debugging.
Change the default compiler's behavior to enable the --nodebugcomments flag and add a new flag to do the reverse: --debugcomments

**Comment by Maiori44** [comment]
this is a good idea, I'll probably add it in the next version

**Comment by Maiori44** [comment]
2.2.1 was released and it changed `--nodebugcomments` into `--debugcomments`
so this issue is now solved and will be closed
