### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by Enn3Developer** [ClueLang/Clue#22]
About docs, I'm not talking of the wiki (although that needs some rework) but about the codebase.
If one wants to start contributing to the project they need first to understand the code they'll work on, and the best way to learn about the code is to read what the code does.
Reading the code as-is may be something really difficult, here's why there's the need of documenting the code: to make the life easier to people that want to contribute on the project.

**Comment by Maiori44** [comment]
I don't think I can document the code myself as im not really great at explaining things

**Comment by Maiori44** [comment]
Should this be done for 3.0?

**Comment by Enn3Developer** [comment]
Yeah, prob after the type system

**Comment by Maiori44** [comment]
I'll add the milestone then

**Comment by Enn3Developer** [comment]
nah, maybe I'll do this one after I'm finished with the optimizations

**Comment by Maiori44** [comment]
Alright

**Comment by Maiori44** [comment]
Since 3.0 is huge and 3.1 is gonna be a sort of "doc and lib" update..maybe this should be delayed to 3.1?
