### ISSUE TITLE
Casing

### ISSUE THREAD

**Issue by Enn3Developer** [ClueLang/Clue#25]
As it is now, the casing is all a mess + some of the functions and variables (and other things) don't follow the standard casing used in Rust.
What should be done about it?

**Comment by Maiori44** [comment]
the reason I don't follow Rust's casing is
I don't really like it personally

**Comment by Enn3Developer** [comment]
why though?
just for reference: https://rust-lang.github.io/api-guidelines/naming.html

**Comment by mintxenva75** [comment]
Change the caseing details to improve rusts functions with there variables and create rusts an improved style of code

**Comment by Maiori44** [comment]
> why though? just for reference: https://rust-lang.github.io/api-guidelines/naming.html

there is no real reason, I simply don't like it lol

**Comment by Maiori44** [comment]
to be more clear, Clue was made with this casing becouse it was originally more of a personal project, as I never expected it to get this known

but now that more people are going to check the code, the casing should be fixed, I'll do it myself

**Comment by Maiori44** [comment]
ok the casing has been fixed in the next branch, and will be fixed in the main branch too once a new version of Clue is out
