### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Enn3Developer** [ClueLang/Clue#27]
After what happened yesterday, the need of testing is rising. Every pr should firstly pass all the test and then can be reviewed.
I'll volunteer on this work.
What tests do you suggest to add?

**Comment by Maiori44** [comment]
Oh yeah, I had an idea for this yesterday but I had forgotten it
I think we should make an example folder with a file for every feature Clue has
Ever PR must compile every file inside that folder + the Clue-example repository to be accepted

**Comment by Markos-Th09** [comment]
We really need to add tests about any language features of clue. Also we should add tests that we expect them to fail for them to pass.
