### ISSUE TITLE
2.5.1's new dependency likely os-dependant 

### ISSUE THREAD

**Issue by Maiori44** [ClueLang/Clue#46]
mlua with the vendored feature seems to only work out of the box for linux, which would mean we should use another dependency (rlua?)

I am not 100% sure if this is the issue with 2.5.1, more testing required

**Comment by Maiori44** [comment]
It might just be that the action needs to be remade, not sure what the fate of this issue should be now

**Comment by Markos-Th09** [comment]
support is ok and I can verify that. cross compilation is a big mess.
