### ISSUE TITLE
[Feature Request] conditional compilation support

### ISSUE THREAD

**Issue by progmboy** [ClueLang/Clue#49]
As we all know that lua has no conditional compilation support, if we develop cross-platform code, lua will compile all the code into bytecode.

like:
```lua
if os.name() == 'windows' then
    -- some code
else
    -- some code
end
```
That will introduces unnecessary code on specific platforms.
So it would be great if the Clue language had conditional compilation support.

like C:

```c
#ifdef xxx
    // code
#else
    // code
#endif
```

or Rust:

```rust
#[cfg(windows)]
//code
```

**Comment by Enn3Developer** [comment]
Dunno if that was already planned as a macro

**Comment by Maiori44** [comment]
Should Clue omit from compilation code that does not match the condition?

**Comment by progmboy** [comment]
> Should Clue omit from compilation code that does not match the condition?

I think yes, the code that does not match should be ignored

**Comment by Markos-Th09** [comment]
conditional compilation is a bit out of the scope of an interpreted language (technically clue is interpreted as it relieves on the lua vm to be executed) as it needs to run everywhere the same.

**Comment by Maiori44** [comment]
Clue is really a compiled lamguage though, Lua is the interpreted one.

**Comment by Markos-Th09** [comment]
> Clue is really a compiled language though, Lua is the interpreted one.

in this context I define compiled as generating machine code. If you target the lua vm then you have to treat clue as an interpreted language. Conditional compilation is a feature that is only useful when targeting a specific platform. It is out of scope because clue is targeting the cross platform lua vm.

**Comment by Maiori44** [comment]
> > Clue is really a compiled language though, Lua is the interpreted one.
> 
> in this context I define compiled as generating machine code. If you target the lua vm then you have to treat clue as an interpreted language. Conditional compilation is a feature that is only useful when targeting a specific platform. It is out of scope because clue is targeting the cross platform lua vm.

With your definition Clue is still not interpreted, it's transpiled.
If I got a C to Lua converter would it make C interpreted?

**Comment by Markos-Th09** [comment]
> > > Clue is really a compiled language though, Lua is the interpreted one.
> > 
> > 
> > in this context I define compiled as generating machine code. If you target the lua vm then you have to treat clue as an interpreted language. Conditional compilation is a feature that is only useful when targeting a specific platform. It is out of scope because clue is targeting the cross platform lua vm.
> 
> With your definition Clue is still not interpreted, it's transpiled. If I got a C to Lua converter would it make C interpreted?

converting C would be different because you would not be targeting an interpreter/vm. So C still remains a compiler language.

**Comment by Maiori44** [comment]
How is a C to Lua converter not targeting an interpreter?

**Comment by Markos-Th09** [comment]
> How is a C to Lua converter not targeting an interpreter?

sorry I misread C to lua

**Comment by Markos-Th09** [comment]
> > How is a C to Lua converter not targeting an interpreter?
> 
> sorry I misread C to lua. My definition is incomplete and I agree that my definition is incomplete but you get what I am trying to say.

**Comment by Maiori44** [comment]
I do get your point sorta but look on the other hand: a preprocessor would improve a lot, make macros much easier and fix some stuff too

**Comment by Markos-Th09** [comment]
> I do get your point sorta but look on the other hand: a preprocessor would improve a lot, make macros much easier and fix some stuff too

A preprocessor is a good thing but conditional compilation is just not something useful

**Comment by Maiori44** [comment]
I mean adding something like #ifdef won't hurt, just a nice extra

**Comment by Markos-Th09** [comment]
Another idea which is kinda related is dead code elimination. Although this is probably a bit complicated.

**Comment by Maiori44** [comment]
Something like that would have to be added after types, so in 4.X

**Comment by Markos-Th09** [comment]
> Something like that would have to be added after types, so in 4.X

The basic idea is finding conditions which coerce to always true and always false and infinite loops, which doesn't really need a type system.

**Comment by Maiori44** [comment]
Yes but the type system will use similar code to figure out types, no need to invent the wheel twice

**Comment by Markos-Th09** [comment]
> Yes but the type system will use similar code to figure out types, no need to invent the wheel twice

I don’t think type system can detect if(0)

**Comment by Maiori44** [comment]
...?

**Comment by Markos-Th09** [comment]
> ...?

```rust
if 0 {
    print("never true")
}
```

**Comment by Maiori44** [comment]
...what are you trying to say?

**Comment by Markos-Th09** [comment]
> ...what are you trying to say?

A type system probably won’t consider 0 as a boolean value

**Comment by Maiori44** [comment]
The type checker would check that an if condition is bool, so it will be able to convert it

**Comment by Markos-Th09** [comment]
> The type checker would check that an if condition is bool, so it will be able to convert it

the point is that we have would have to do type coercion. this isn’t a feature we would need right now so I think we can save it for 4.0 anyways.

**Comment by Maiori44** [comment]
Saving it for 4.0 is what I was trying to say

**Comment by Markos-Th09** [comment]
> Saving it for 4.0 is what I was trying to say

Didn’t say anything against that

**Comment by Maiori44** [comment]
Guess this argument was kind of a mess then lol

**Comment by Markos-Th09** [comment]
> Guess this argument was kind of a mess then lol

yeah lol this issue is a mess

**Comment by Maiori44** [comment]
The preprocessor in Clue 3.0 fixes this issue using `@ifos`, so this can be closed
