### ISSUE TITLE
what is the scanner based on ?

### ISSUE THREAD

**Issue by usernamedd** [ClueLang/Clue#5]
I have learned compiler knowledge , As far as I know , the scanner is based on transiton graph or nfa or dfa or regular expression . When I read the source code of scanner , few information about these terms present.
How do you start the scanner under the hood?

**Comment by Maiori44** [comment]
The scanner was made when I was still using a book to figure it out, but the book used another language (Java) so I had to rewrite the code myself, and so I used my own names for stuff
I think scanner itself was given by me, so it may be a different thing altogether
(Clue's scanner simply reads a file and converts words and symbols into tokens)

**Comment by Markos-Th09** [comment]
Maybe a better name for scanner would be lexer since it is a compiler

**Comment by Maiori44** [comment]
hm, I'll do some research for it later

**Comment by Maiori44** [comment]
I checked the book that I read when making the scanner (craftinginterpreters.com)
And it says this:
> This task has been variously called “scanning” and “lexing” (short for “lexical analysis”) over the years. Way back when computers were as big as Winnebagos but had less memory than your watch, some people used “scanner” only to refer to the piece of code that dealt with reading raw source code characters from disk and buffering them in memory. Then “lexing” was the subsequent phase that did useful stuff with the characters.
> These days, reading a source file into memory is trivial, so it’s rarely a distinct phase in the compiler. Because of that, the two terms are basically interchangeable.

So I think calling it scanner is not wrong

**Comment by usernamedd** [comment]
In fact , what I focused on is  the theory on which the scanner implementation depend. From a begenner's point of view, implementing a lexer or scanner need kind of like NFA DFA or transform graph theory . But a bit confused that I can not find the theory knowledge from the source code .that is why  I do not know how to start a lexer from scaraching.

**Comment by Markos-Th09** [comment]
There is that really fine line between the scanner and the lexer. By looking at it more in depth it is kinda both

**Comment by Maiori44** [comment]
> In fact , what I focused on is  the theory on which the scanner implementation depend. From a begenner's point of view, implementing a lexer or scanner need kind of like NFA DFA or transform graph theory . But a bit confused that I can not find the theory knowledge from the source code .that is why  I do not know how to start a lexer from scaraching.

Oh, maybe that's because there are no comments in the code

**Comment by usernamedd** [comment]
> > In fact , what I focused on is  the theory on which the scanner implementation depend. From a begenner's point of view, implementing a lexer or scanner need kind of like NFA DFA or transform graph theory . But a bit confused that I can not find the theory knowledge from the source code .that is why  I do not know how to start a lexer from scaraching.
> 
> Oh, maybe that's because there are no comments in the code

what about your notes ,or blog describe what and how you organize codes

**Comment by Maiori44** [comment]
honestly, I'm not good at explaining how I organize stuff so it was never written anywhere, it's all only in my mind
