### ISSUE TITLE
Library interface for clue

### ISSUE THREAD

**Issue by Markos-Th09** [ClueLang/Clue#57]
Clue needs a good library interface to be properly embeddable.

**Comment by Maiori44** [comment]
Still unsure if this should be for 3.0 or 3.1

**Comment by Enn3Developer** [comment]
Def 3.0

**Comment by Maiori44** [comment]
Considering 3.0 already has a **lot** and there seems to be issues that would be tricky to handle, I'll likely delay this to 3.1

**Comment by Markos-Th09** [comment]
> Considering 3.0 already has a **lot** and there seems to be issues that would be tricky to handle, I'll likely delay this to 3.1

We have to delay this because it would be another big refactor

**Comment by Maiori44** [comment]
Once we add this it should probably be it's own member in the workspace
