### ISSUE TITLE
Merge Clue-wasm and Clue

### ISSUE THREAD

**Issue by Maiori44** [ClueLang/Clue#58]
Since Clue-wasm is very outdated and Clue 3.0 will already use Cargo's workspace feature we could use it to merge the 2 repositories together.

**Comment by Markos-Th09** [comment]
With the introduction of clue_core the outdated part of this has been resolved, although merging it to the workspace is still undecided

**Comment by Maiori44** [comment]
considering how unsure we are and the fact 3.1 is big already, maybe we should do this in 3.2 instead?

**Comment by Maiori44** [comment]
It has been decided that Clue-wasm will be integrated into clue_core in 3.2
