### ISSUE TITLE
Allow to choose target

### ISSUE THREAD

**Issue by Maiori44** [ClueLang/Clue#67]
Adding a `--target` flag for cross compiling
Since 3.0 is feature locked, this will be added in 3.1

**Comment by Maiori44** [comment]
making this issue more general to also include choosing the lua target, which is far more useful

**Comment by Enn3Developer** [comment]
Then I think another target to add should be LLVM (but this may be for 5.0 or further down the road)

**Comment by Maiori44** [comment]
`--target` and `--targetos` were added in 3.1
