### ISSUE TITLE
Clippy errors

### ISSUE THREAD

**Issue by Enn3Developer** [ClueLang/Clue#72]
Running the current `next` branch with `cargo clippy -- -D clippy::correctness -D clippy::complexity -D clippy::pedantic -D clippy::nursery -D clippy::perf -D clippy::cargo -D clippy::restriction` gives 1425 errors and 4 warnings.
I'm pretty sure some stuff is useful to resolve but not everything
Prob for 3.1 but can later be changed to 3.X or 4.0

**Comment by Maiori44** [comment]
I think this is a bit too much and probably doesn't matter 
Definitely not for 3.1

**Comment by Enn3Developer** [comment]
Without the restriction bit (it seems all to be documentation problems) it only complains about 118 errors

**Comment by Maiori44** [comment]
eh..this still seems not much important

**Comment by Markos-Th09** [comment]
Most of the issues are either docs, opinionated or unimportant

**Comment by Markos-Th09** [comment]
> Running the current `next` branch with `cargo clippy -- -D clippy::correctness -D clippy::complexity -D clippy::pedantic -D clippy::nursery -D clippy::perf -D clippy::cargo -D clippy::restriction` gives 1425 errors and 4 warnings. I'm pretty sure some stuff is useful to resolve but not everything Prob for 3.1 but can later be changed to 3.X or 4.0

This means nothing because some these lints are meant to be opinionated we actually need a list of lints that we agree with
