### ISSUE TITLE
[Idea] Compiler from Lua to clue

### ISSUE THREAD

**Issue by Markos-Th09** [ClueLang/Clue#8]
If for example you had a big Lua codebase that you wanted to convert to clue it would be a bit of a pain. The job of this compiler would be to convert Lua code blocks(then/do/repeat, end/until) into clue code blocks (curly braces). The difficult part on this is parsing Lua.

Edit: I might try to implement it myself

**Comment by Maiori44** [comment]
I had this idea a while ago, but never started it becouse it would have taken a long time
if you do try to do it yourself it'd be great if you could join the ClueLang organization and make a repo for it there
do you have Discord? we could discuss that there

**Comment by Markos-Th09** [comment]
> I had this idea a while ago, but never started it becouse it would have taken a long time if you do try to do it yourself it'd be great if you could join the ClueLang organization and make a repo for it there do you have Discord? we could discuss that there

I do. My username is MarkosTh09#2759

**Comment by Markos-Th09** [comment]
This is currently being worked on https://github.com/ClueLang/Find

**Comment by Markos-Th09** [comment]
I can pretty much say find is pretty much dead right now

**Comment by Maiori44** [comment]
At least a beta was released

**Comment by Markos-Th09** [comment]
I started working on the project again and I will close once I have a good enough tool
